#!/usr/bin/perl
use strict;
use warnings;


## sequence of index primers,
## $primer5 is the universal primer for NEB Ultra library preparation kit, $SR_primer is the universal primer for NEB Small RNA library preparation kit

my %SampleIndex;
$index1='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACATCACGATCTCGTATGCCGTCTTCTGCTTG';
$index2='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACCGATGTATCTCGTATGCCGTCTTCTGCTTG';
$index3='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACTTAGGCATCTCGTATGCCGTCTTCTGCTTG';
$index4='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACTGACCAATCTCGTATGCCGTCTTCTGCTTG';
$index5='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACACAGTGATCTCGTATGCCGTCTTCTGCTTG';
$index6='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTTCTGCTTG';
$index7='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACCAGATCATCTCGTATGCCGTCTTCTGCTTG';
$index8='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACACTTGAATCTCGTATGCCGTCTTCTGCTTG';
$index9='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGATCAGATCTCGTATGCCGTCTTCTGCTTG';
$index10='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACTAGCTTATCTCGTATGCCGTCTTCTGCTTG';
$index11='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGGCTACATCTCGTATGCCGTCTTCTGCTTG';
$index12='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACCTTGTAATCTCGTATGCCGTCTTCTGCTTG';
$index13='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACAGTCAACAATCTCGTATGCCGTCTTCTGCTTG';
$index14='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACAGTTCCGTATCTCGTATGCCGTCTTCTGCTTG';
$index15='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACATGTCAGAATCTCGTATGCCGTCTTCTGCTTG';
$index16='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACCCGTCCATCTCGTATGCCGTCTTCTGCTTG';
$index18='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGTCCGCACATCTCGTATGCCGTCTTCTGCTTG';
$index19='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGTGAAACGATCTCGTATGCCGTCTTCTGCTTG';
$index20='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGTGGCCTTATCTCGTATGCCGTCTTCTGCTTG';
$index21='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGTTTCGGAATCTCGTATGCCGTCTTCTGCTTG';
$index22='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACCGTACGTAATCTCGTATGCCGTCTTCTGCTTG';
$index23='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGAGTGGATATCTCGTATGCCGTCTTCTGCTTG';
$index25='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACACTGATATATCTCGTATGCCGTCTTCTGCTTG';
$index27='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACATTCCTTTATCTCGTATGCCGTCTTCTGCTTG';
$primer5='AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT';
$SR_primer='GATCGTCGGACTGTAGAACTCTGAACGTGTAGATCTCGGTGGTCGCCGTATCATT'; 

## Assign sample names with indexs
$SampleIndex{'1-IP'}=$index1;
$SampleIndex{'1-C'}=$index2;

@Sample=(keys %SampleIndex);

## cutadapt, universal primer can be modified according to the different library preparation kit.
foreach(@Sample){
    system("cutadapt -m 20 -a $SampleIndex{$_} -A $primer5 -o $_.trimmed.2.R1.fq.gz -p $_.trimmed.2.R2.fq.gz $_.R1.fastq.gz $_.R2.fastq.gz");
}

## mapping and file conversion
foreach(@Sample){
    system(
        "hisat2 -p 15 -x /media/l/af88f09f-4530-4fa9-94fc-0ce7fbe4aa5f/refgenome/homo_sapiens/GRCh38.spike.in -1 $_.trimmed.2.R1.fq.gz -2 $_.trimmed.2.R2.fq.gz -S $_.sam
         samtools view -bS $_.sam > $_.bam
         samtools sort -o $_.sorted.bam $_.bam
         samtools index $_.sorted.bam
         rm -rf $_.bam
         rm -rf $_.sam"
   );
}

## statistics of mapping 

foreach(@Sample){
    system(
    	  "echo $_ >> mapping_report.txt
    	   samtools flagstat $_.bam >> mapping_report.txt
         echo 'unique mapping' >> mapping_report.txt
         samtools view $_.bam | grep NH:i:1 | wc -l >> mapping_report.txt"
    );
}




